// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv_2d_cl_array_array_ap_fixed_8u_config2_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        data_V_data_V_dout,
        data_V_data_V_empty_n,
        data_V_data_V_read,
        res_V_data_0_V_din,
        res_V_data_0_V_full_n,
        res_V_data_0_V_write,
        res_V_data_1_V_din,
        res_V_data_1_V_full_n,
        res_V_data_1_V_write,
        res_V_data_2_V_din,
        res_V_data_2_V_full_n,
        res_V_data_2_V_write,
        res_V_data_3_V_din,
        res_V_data_3_V_full_n,
        res_V_data_3_V_write,
        res_V_data_4_V_din,
        res_V_data_4_V_full_n,
        res_V_data_4_V_write,
        res_V_data_5_V_din,
        res_V_data_5_V_full_n,
        res_V_data_5_V_write,
        res_V_data_6_V_din,
        res_V_data_6_V_full_n,
        res_V_data_6_V_write,
        res_V_data_7_V_din,
        res_V_data_7_V_full_n,
        res_V_data_7_V_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state6 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [15:0] data_V_data_V_dout;
input   data_V_data_V_empty_n;
output   data_V_data_V_read;
output  [15:0] res_V_data_0_V_din;
input   res_V_data_0_V_full_n;
output   res_V_data_0_V_write;
output  [15:0] res_V_data_1_V_din;
input   res_V_data_1_V_full_n;
output   res_V_data_1_V_write;
output  [15:0] res_V_data_2_V_din;
input   res_V_data_2_V_full_n;
output   res_V_data_2_V_write;
output  [15:0] res_V_data_3_V_din;
input   res_V_data_3_V_full_n;
output   res_V_data_3_V_write;
output  [15:0] res_V_data_4_V_din;
input   res_V_data_4_V_full_n;
output   res_V_data_4_V_write;
output  [15:0] res_V_data_5_V_din;
input   res_V_data_5_V_full_n;
output   res_V_data_5_V_write;
output  [15:0] res_V_data_6_V_din;
input   res_V_data_6_V_full_n;
output   res_V_data_6_V_write;
output  [15:0] res_V_data_7_V_din;
input   res_V_data_7_V_full_n;
output   res_V_data_7_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg data_V_data_V_read;
reg res_V_data_0_V_write;
reg res_V_data_1_V_write;
reg res_V_data_2_V_write;
reg res_V_data_3_V_write;
reg res_V_data_4_V_write;
reg res_V_data_5_V_write;
reg res_V_data_6_V_write;
reg res_V_data_7_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire   [1:0] w2_V_address0;
reg    w2_V_ce0;
wire   [376:0] w2_V_q0;
reg   [31:0] pX;
reg   [31:0] sX;
reg   [31:0] pY;
reg   [31:0] sY;
reg   [15:0] kernel_data_V_1;
reg   [15:0] kernel_data_V_2;
reg   [15:0] kernel_data_V_4;
reg   [15:0] kernel_data_V_5;
reg   [15:0] kernel_data_V_7;
reg   [15:0] kernel_data_V_8;
reg   [15:0] kernel_data_V_0;
reg   [15:0] kernel_data_V_3;
reg   [15:0] kernel_data_V_6;
reg    data_V_data_V_blk_n;
wire    ap_CS_fsm_state2;
reg    res_V_data_0_V_blk_n;
wire    ap_CS_fsm_state6;
reg   [0:0] and_ln272_2_reg_2341;
reg    res_V_data_1_V_blk_n;
reg    res_V_data_2_V_blk_n;
reg    res_V_data_3_V_blk_n;
reg    res_V_data_4_V_blk_n;
reg    res_V_data_5_V_blk_n;
reg    res_V_data_6_V_blk_n;
reg    res_V_data_7_V_blk_n;
reg   [1:0] w_index22_reg_399;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
reg   [15:0] tmp_data_0_V_820_reg_675;
reg   [15:0] tmp_data_1_V_418_reg_686;
reg   [15:0] tmp_data_2_V_416_reg_697;
reg   [15:0] tmp_data_3_V_414_reg_708;
reg   [15:0] tmp_data_4_V_412_reg_719;
reg   [15:0] tmp_data_5_V_410_reg_730;
reg   [15:0] tmp_data_6_V_48_reg_741;
reg   [15:0] tmp_data_7_V_46_reg_752;
reg   [31:0] sX_load_reg_2309;
wire   [0:0] icmp_ln272_fu_913_p2;
reg   [0:0] icmp_ln272_reg_2314;
reg   [31:0] sY_load_reg_2319;
wire   [0:0] icmp_ln272_1_fu_923_p2;
reg   [0:0] icmp_ln272_1_reg_2324;
reg   [31:0] pY_load_reg_2329;
reg   [31:0] pX_load_reg_2335;
wire   [0:0] and_ln272_2_fu_981_p2;
wire   [6:0] add_ln78_fu_987_p2;
reg   [6:0] add_ln78_reg_2345;
wire   [1:0] w_index_fu_993_p2;
reg   [1:0] w_index_reg_2350;
reg    ap_enable_reg_pp0_iter0;
reg   [1:0] ap_phi_mux_w_index22_phi_fu_403_p4;
wire   [0:0] icmp_ln64_fu_1268_p2;
reg   [0:0] icmp_ln64_reg_2720;
reg   [0:0] icmp_ln64_reg_2720_pp0_iter1_reg;
reg   [15:0] trunc_ln_reg_2724;
wire   [15:0] add_ln703_fu_1349_p2;
reg   [15:0] add_ln703_reg_2729;
reg   [15:0] trunc_ln708_1024_reg_2734;
wire   [15:0] add_ln703_1026_fu_1436_p2;
reg   [15:0] add_ln703_1026_reg_2739;
reg   [15:0] trunc_ln708_1027_reg_2744;
wire   [15:0] add_ln703_1029_fu_1523_p2;
reg   [15:0] add_ln703_1029_reg_2749;
reg   [15:0] trunc_ln708_1030_reg_2754;
wire   [15:0] add_ln703_1032_fu_1610_p2;
reg   [15:0] add_ln703_1032_reg_2759;
reg   [15:0] trunc_ln708_1033_reg_2764;
wire   [15:0] add_ln703_1035_fu_1697_p2;
reg   [15:0] add_ln703_1035_reg_2769;
reg   [15:0] trunc_ln708_1036_reg_2774;
wire   [15:0] add_ln703_1038_fu_1784_p2;
reg   [15:0] add_ln703_1038_reg_2779;
reg   [15:0] trunc_ln708_1039_reg_2784;
wire   [15:0] add_ln703_1041_fu_1871_p2;
reg   [15:0] add_ln703_1041_reg_2789;
reg   [15:0] trunc_ln708_1042_reg_2794;
wire   [15:0] add_ln703_1044_fu_1962_p2;
reg   [15:0] add_ln703_1044_reg_2799;
wire   [15:0] acc_0_V_fu_1972_p2;
reg   [15:0] acc_0_V_reg_2804;
reg    ap_enable_reg_pp0_iter2;
wire   [15:0] acc_1_V_fu_1982_p2;
reg   [15:0] acc_1_V_reg_2810;
wire   [15:0] acc_2_V_fu_1992_p2;
reg   [15:0] acc_2_V_reg_2816;
wire   [15:0] acc_3_V_fu_2002_p2;
reg   [15:0] acc_3_V_reg_2822;
wire   [15:0] acc_4_V_fu_2012_p2;
reg   [15:0] acc_4_V_reg_2828;
wire   [15:0] acc_5_V_fu_2022_p2;
reg   [15:0] acc_5_V_reg_2834;
wire   [15:0] acc_6_V_fu_2032_p2;
reg   [15:0] acc_6_V_reg_2840;
wire   [15:0] acc_7_V_fu_2042_p2;
reg   [15:0] acc_7_V_reg_2846;
wire    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter1;
reg    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_start;
wire    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_done;
wire    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_idle;
wire    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_ready;
wire   [15:0] call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_0;
wire   [15:0] call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_1;
wire   [15:0] call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_2;
wire   [15:0] call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_3;
wire   [15:0] call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_4;
wire   [15:0] call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_5;
wire   [15:0] call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_6;
wire   [15:0] call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_7;
wire   [15:0] call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_8;
reg   [6:0] indvar_flatten23_reg_387;
reg    ap_block_state1;
wire    io_acc_block_signal_op423;
reg    ap_block_state6;
wire   [0:0] icmp_ln78_fu_2135_p2;
wire    ap_block_pp0_stage0;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_reg_411;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_reg_411;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_1_reg_422;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_1_reg_422;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_2_reg_433;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_2_reg_433;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_3_reg_444;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_3_reg_444;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_4_reg_455;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_4_reg_455;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_5_reg_466;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_5_reg_466;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_6_reg_477;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_6_reg_477;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_7_reg_488;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_7_reg_488;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_8_reg_499;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_8_reg_499;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_9_reg_510;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_9_reg_510;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_10_reg_521;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_10_reg_521;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_11_reg_532;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_11_reg_532;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_12_reg_543;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_12_reg_543;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_13_reg_554;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_13_reg_554;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_14_reg_565;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_14_reg_565;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_15_reg_576;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_15_reg_576;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_16_reg_587;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_16_reg_587;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_17_reg_598;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_17_reg_598;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_18_reg_609;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_18_reg_609;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_19_reg_620;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_19_reg_620;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_20_reg_631;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_20_reg_631;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_21_reg_642;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_21_reg_642;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_22_reg_653;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_22_reg_653;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln76_23_reg_664;
reg  signed [15:0] ap_phi_reg_pp0_iter1_phi_ln76_23_reg_664;
wire   [31:0] select_ln303_fu_2115_p3;
reg   [31:0] ap_phi_mux_storemerge_i_i_phi_fu_766_p4;
wire   [0:0] icmp_ln293_fu_2048_p2;
wire   [0:0] icmp_ln297_fu_2094_p2;
wire   [63:0] zext_ln76_fu_1003_p1;
wire   [31:0] add_ln306_fu_2053_p2;
wire   [31:0] select_ln308_fu_2069_p3;
wire   [31:0] add_ln301_fu_2099_p2;
wire   [30:0] tmp_fu_933_p4;
wire   [30:0] tmp_1_fu_953_p4;
wire   [0:0] icmp_ln272_2_fu_943_p2;
wire   [0:0] icmp_ln272_3_fu_963_p2;
wire   [0:0] and_ln272_1_fu_975_p2;
wire   [0:0] and_ln272_fu_969_p2;
wire  signed [15:0] trunc_ln76_fu_1274_p1;
wire  signed [25:0] mul_ln1118_fu_2141_p2;
wire  signed [15:0] tmp_1023_fu_1295_p4;
wire  signed [25:0] mul_ln1118_1024_fu_2148_p2;
wire  signed [15:0] tmp_1024_fu_1322_p4;
wire  signed [25:0] mul_ln1118_1025_fu_2155_p2;
wire   [15:0] trunc_ln708_s_fu_1313_p4;
wire   [15:0] trunc_ln708_1023_fu_1340_p4;
wire  signed [15:0] tmp_1025_fu_1355_p4;
wire  signed [25:0] mul_ln1118_1026_fu_2162_p2;
wire  signed [15:0] tmp_1026_fu_1382_p4;
wire  signed [25:0] mul_ln1118_1027_fu_2169_p2;
wire  signed [15:0] tmp_1027_fu_1409_p4;
wire  signed [25:0] mul_ln1118_1028_fu_2176_p2;
wire   [15:0] trunc_ln708_1025_fu_1400_p4;
wire   [15:0] trunc_ln708_1026_fu_1427_p4;
wire  signed [15:0] tmp_1028_fu_1442_p4;
wire  signed [25:0] mul_ln1118_1029_fu_2183_p2;
wire  signed [15:0] tmp_1029_fu_1469_p4;
wire  signed [25:0] mul_ln1118_1030_fu_2190_p2;
wire  signed [15:0] tmp_1030_fu_1496_p4;
wire  signed [25:0] mul_ln1118_1031_fu_2197_p2;
wire   [15:0] trunc_ln708_1028_fu_1487_p4;
wire   [15:0] trunc_ln708_1029_fu_1514_p4;
wire  signed [15:0] tmp_1031_fu_1529_p4;
wire  signed [25:0] mul_ln1118_1032_fu_2204_p2;
wire  signed [15:0] tmp_1032_fu_1556_p4;
wire  signed [25:0] mul_ln1118_1033_fu_2211_p2;
wire  signed [15:0] tmp_1033_fu_1583_p4;
wire  signed [25:0] mul_ln1118_1034_fu_2218_p2;
wire   [15:0] trunc_ln708_1031_fu_1574_p4;
wire   [15:0] trunc_ln708_1032_fu_1601_p4;
wire  signed [15:0] tmp_1034_fu_1616_p4;
wire  signed [25:0] mul_ln1118_1035_fu_2225_p2;
wire  signed [15:0] tmp_1035_fu_1643_p4;
wire  signed [25:0] mul_ln1118_1036_fu_2232_p2;
wire  signed [15:0] tmp_1036_fu_1670_p4;
wire  signed [25:0] mul_ln1118_1037_fu_2239_p2;
wire   [15:0] trunc_ln708_1034_fu_1661_p4;
wire   [15:0] trunc_ln708_1035_fu_1688_p4;
wire  signed [15:0] tmp_1037_fu_1703_p4;
wire  signed [25:0] mul_ln1118_1038_fu_2246_p2;
wire  signed [15:0] tmp_1038_fu_1730_p4;
wire  signed [25:0] mul_ln1118_1039_fu_2253_p2;
wire  signed [15:0] tmp_1039_fu_1757_p4;
wire  signed [25:0] mul_ln1118_1040_fu_2260_p2;
wire   [15:0] trunc_ln708_1037_fu_1748_p4;
wire   [15:0] trunc_ln708_1038_fu_1775_p4;
wire  signed [15:0] tmp_1040_fu_1790_p4;
wire  signed [25:0] mul_ln1118_1041_fu_2267_p2;
wire  signed [15:0] tmp_1041_fu_1817_p4;
wire  signed [25:0] mul_ln1118_1042_fu_2274_p2;
wire  signed [15:0] tmp_1042_fu_1844_p4;
wire  signed [25:0] mul_ln1118_1043_fu_2281_p2;
wire   [15:0] trunc_ln708_1040_fu_1835_p4;
wire   [15:0] trunc_ln708_1041_fu_1862_p4;
wire  signed [15:0] tmp_1043_fu_1877_p4;
wire  signed [25:0] mul_ln1118_1044_fu_2288_p2;
wire  signed [15:0] tmp_1044_fu_1904_p4;
wire  signed [25:0] mul_ln1118_1045_fu_2295_p2;
wire  signed [8:0] tmp_1045_fu_1931_p4;
wire  signed [24:0] mul_ln1118_1046_fu_2302_p2;
wire   [14:0] trunc_ln708_1044_fu_1949_p4;
wire   [15:0] trunc_ln708_1043_fu_1922_p4;
wire  signed [15:0] sext_ln708_fu_1958_p1;
wire   [15:0] add_ln703_1024_fu_1968_p2;
wire   [15:0] add_ln703_1027_fu_1978_p2;
wire   [15:0] add_ln703_1030_fu_1988_p2;
wire   [15:0] add_ln703_1033_fu_1998_p2;
wire   [15:0] add_ln703_1036_fu_2008_p2;
wire   [15:0] add_ln703_1039_fu_2018_p2;
wire   [15:0] add_ln703_1042_fu_2028_p2;
wire   [15:0] add_ln703_1045_fu_2038_p2;
wire   [31:0] add_ln308_fu_2064_p2;
wire   [31:0] add_ln303_fu_2110_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_223;
reg    ap_condition_483;
reg    ap_condition_611;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 pX = 32'd0;
#0 sX = 32'd0;
#0 pY = 32'd0;
#0 sY = 32'd0;
#0 kernel_data_V_1 = 16'd0;
#0 kernel_data_V_2 = 16'd0;
#0 kernel_data_V_4 = 16'd0;
#0 kernel_data_V_5 = 16'd0;
#0 kernel_data_V_7 = 16'd0;
#0 kernel_data_V_8 = 16'd0;
#0 kernel_data_V_0 = 16'd0;
#0 kernel_data_V_3 = 16'd0;
#0 kernel_data_V_6 = 16'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

conv_2d_cl_array_array_ap_fixed_8u_config2_s_w2_V #(
    .DataWidth( 377 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
w2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_V_address0),
    .ce0(w2_V_ce0),
    .q0(w2_V_q0)
);

shift_line_buffer_array_ap_fixed_1u_config2_s call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_start),
    .ap_done(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_done),
    .ap_idle(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_idle),
    .ap_ready(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_ready),
    .in_elem_data_V_read(data_V_data_V_dout),
    .kernel_window_1_V_read(kernel_data_V_1),
    .kernel_window_2_V_read(kernel_data_V_2),
    .kernel_window_4_V_read(kernel_data_V_4),
    .kernel_window_5_V_read(kernel_data_V_5),
    .kernel_window_7_V_read(kernel_data_V_7),
    .kernel_window_8_V_read(kernel_data_V_8),
    .ap_return_0(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_0),
    .ap_return_1(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_1),
    .ap_return_2(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_2),
    .ap_return_3(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_3),
    .ap_return_4(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_4),
    .ap_return_5(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_5),
    .ap_return_6(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_6),
    .ap_return_7(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_7),
    .ap_return_8(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_8)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U14(
    .din0(ap_phi_reg_pp0_iter1_phi_ln76_reg_411),
    .din1(trunc_ln76_fu_1274_p1),
    .dout(mul_ln1118_fu_2141_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U15(
    .din0(tmp_1023_fu_1295_p4),
    .din1(ap_phi_reg_pp0_iter1_phi_ln76_1_reg_422),
    .dout(mul_ln1118_1024_fu_2148_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U16(
    .din0(tmp_1024_fu_1322_p4),
    .din1(ap_phi_reg_pp0_iter1_phi_ln76_2_reg_433),
    .dout(mul_ln1118_1025_fu_2155_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U17(
    .din0(tmp_1025_fu_1355_p4),
    .din1(ap_phi_reg_pp0_iter1_phi_ln76_3_reg_444),
    .dout(mul_ln1118_1026_fu_2162_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U18(
    .din0(tmp_1026_fu_1382_p4),
    .din1(ap_phi_reg_pp0_iter1_phi_ln76_4_reg_455),
    .dout(mul_ln1118_1027_fu_2169_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U19(
    .din0(tmp_1027_fu_1409_p4),
    .din1(ap_phi_reg_pp0_iter1_phi_ln76_5_reg_466),
    .dout(mul_ln1118_1028_fu_2176_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U20(
    .din0(tmp_1028_fu_1442_p4),
    .din1(ap_phi_reg_pp0_iter1_phi_ln76_6_reg_477),
    .dout(mul_ln1118_1029_fu_2183_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U21(
    .din0(tmp_1029_fu_1469_p4),
    .din1(ap_phi_reg_pp0_iter1_phi_ln76_7_reg_488),
    .dout(mul_ln1118_1030_fu_2190_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U22(
    .din0(tmp_1030_fu_1496_p4),
    .din1(ap_phi_reg_pp0_iter1_phi_ln76_8_reg_499),
    .dout(mul_ln1118_1031_fu_2197_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U23(
    .din0(tmp_1031_fu_1529_p4),
    .din1(ap_phi_reg_pp0_iter1_phi_ln76_9_reg_510),
    .dout(mul_ln1118_1032_fu_2204_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U24(
    .din0(tmp_1032_fu_1556_p4),
    .din1(ap_phi_reg_pp0_iter1_phi_ln76_10_reg_521),
    .dout(mul_ln1118_1033_fu_2211_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U25(
    .din0(tmp_1033_fu_1583_p4),
    .din1(ap_phi_reg_pp0_iter1_phi_ln76_11_reg_532),
    .dout(mul_ln1118_1034_fu_2218_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U26(
    .din0(tmp_1034_fu_1616_p4),
    .din1(ap_phi_reg_pp0_iter1_phi_ln76_12_reg_543),
    .dout(mul_ln1118_1035_fu_2225_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U27(
    .din0(tmp_1035_fu_1643_p4),
    .din1(ap_phi_reg_pp0_iter1_phi_ln76_13_reg_554),
    .dout(mul_ln1118_1036_fu_2232_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U28(
    .din0(tmp_1036_fu_1670_p4),
    .din1(ap_phi_reg_pp0_iter1_phi_ln76_14_reg_565),
    .dout(mul_ln1118_1037_fu_2239_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U29(
    .din0(tmp_1037_fu_1703_p4),
    .din1(ap_phi_reg_pp0_iter1_phi_ln76_15_reg_576),
    .dout(mul_ln1118_1038_fu_2246_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U30(
    .din0(tmp_1038_fu_1730_p4),
    .din1(ap_phi_reg_pp0_iter1_phi_ln76_16_reg_587),
    .dout(mul_ln1118_1039_fu_2253_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U31(
    .din0(tmp_1039_fu_1757_p4),
    .din1(ap_phi_reg_pp0_iter1_phi_ln76_17_reg_598),
    .dout(mul_ln1118_1040_fu_2260_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U32(
    .din0(tmp_1040_fu_1790_p4),
    .din1(ap_phi_reg_pp0_iter1_phi_ln76_18_reg_609),
    .dout(mul_ln1118_1041_fu_2267_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U33(
    .din0(tmp_1041_fu_1817_p4),
    .din1(ap_phi_reg_pp0_iter1_phi_ln76_19_reg_620),
    .dout(mul_ln1118_1042_fu_2274_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U34(
    .din0(tmp_1042_fu_1844_p4),
    .din1(ap_phi_reg_pp0_iter1_phi_ln76_20_reg_631),
    .dout(mul_ln1118_1043_fu_2281_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U35(
    .din0(tmp_1043_fu_1877_p4),
    .din1(ap_phi_reg_pp0_iter1_phi_ln76_21_reg_642),
    .dout(mul_ln1118_1044_fu_2288_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U36(
    .din0(tmp_1044_fu_1904_p4),
    .din1(ap_phi_reg_pp0_iter1_phi_ln76_22_reg_653),
    .dout(mul_ln1118_1045_fu_2295_p2)
);

myproject_mul_mul_16s_9s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
myproject_mul_mul_16s_9s_25_1_1_U37(
    .din0(ap_phi_reg_pp0_iter1_phi_ln76_23_reg_664),
    .din1(tmp_1045_fu_1931_p4),
    .dout(mul_ln1118_1046_fu_2302_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((io_acc_block_signal_op423 == 1'b0) & (1'd1 == and_ln272_2_reg_2341)) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln78_fu_2135_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln64_fu_1268_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((data_V_data_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2) & (1'd1 == and_ln272_2_fu_981_p2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((data_V_data_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2) & (1'd1 == and_ln272_2_fu_981_p2))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_10_reg_521 <= kernel_data_V_5;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_10_reg_521 <= kernel_data_V_4;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_10_reg_521 <= kernel_data_V_3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_10_reg_521 <= ap_phi_reg_pp0_iter0_phi_ln76_10_reg_521;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_11_reg_532 <= kernel_data_V_8;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_11_reg_532 <= kernel_data_V_7;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_11_reg_532 <= kernel_data_V_6;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_11_reg_532 <= ap_phi_reg_pp0_iter0_phi_ln76_11_reg_532;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_12_reg_543 <= kernel_data_V_2;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_12_reg_543 <= kernel_data_V_1;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_12_reg_543 <= kernel_data_V_0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_12_reg_543 <= ap_phi_reg_pp0_iter0_phi_ln76_12_reg_543;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_13_reg_554 <= kernel_data_V_5;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_13_reg_554 <= kernel_data_V_4;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_13_reg_554 <= kernel_data_V_3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_13_reg_554 <= ap_phi_reg_pp0_iter0_phi_ln76_13_reg_554;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_14_reg_565 <= kernel_data_V_8;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_14_reg_565 <= kernel_data_V_7;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_14_reg_565 <= kernel_data_V_6;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_14_reg_565 <= ap_phi_reg_pp0_iter0_phi_ln76_14_reg_565;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_15_reg_576 <= kernel_data_V_2;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_15_reg_576 <= kernel_data_V_1;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_15_reg_576 <= kernel_data_V_0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_15_reg_576 <= ap_phi_reg_pp0_iter0_phi_ln76_15_reg_576;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_16_reg_587 <= kernel_data_V_5;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_16_reg_587 <= kernel_data_V_4;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_16_reg_587 <= kernel_data_V_3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_16_reg_587 <= ap_phi_reg_pp0_iter0_phi_ln76_16_reg_587;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_17_reg_598 <= kernel_data_V_8;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_17_reg_598 <= kernel_data_V_7;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_17_reg_598 <= kernel_data_V_6;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_17_reg_598 <= ap_phi_reg_pp0_iter0_phi_ln76_17_reg_598;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_18_reg_609 <= kernel_data_V_2;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_18_reg_609 <= kernel_data_V_1;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_18_reg_609 <= kernel_data_V_0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_18_reg_609 <= ap_phi_reg_pp0_iter0_phi_ln76_18_reg_609;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_19_reg_620 <= kernel_data_V_5;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_19_reg_620 <= kernel_data_V_4;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_19_reg_620 <= kernel_data_V_3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_19_reg_620 <= ap_phi_reg_pp0_iter0_phi_ln76_19_reg_620;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_1_reg_422 <= kernel_data_V_5;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_1_reg_422 <= kernel_data_V_4;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_1_reg_422 <= kernel_data_V_3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_1_reg_422 <= ap_phi_reg_pp0_iter0_phi_ln76_1_reg_422;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_20_reg_631 <= kernel_data_V_8;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_20_reg_631 <= kernel_data_V_7;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_20_reg_631 <= kernel_data_V_6;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_20_reg_631 <= ap_phi_reg_pp0_iter0_phi_ln76_20_reg_631;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_21_reg_642 <= kernel_data_V_2;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_21_reg_642 <= kernel_data_V_1;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_21_reg_642 <= kernel_data_V_0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_21_reg_642 <= ap_phi_reg_pp0_iter0_phi_ln76_21_reg_642;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_22_reg_653 <= kernel_data_V_5;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_22_reg_653 <= kernel_data_V_4;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_22_reg_653 <= kernel_data_V_3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_22_reg_653 <= ap_phi_reg_pp0_iter0_phi_ln76_22_reg_653;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_23_reg_664 <= kernel_data_V_8;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_23_reg_664 <= kernel_data_V_7;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_23_reg_664 <= kernel_data_V_6;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_23_reg_664 <= ap_phi_reg_pp0_iter0_phi_ln76_23_reg_664;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_2_reg_433 <= kernel_data_V_8;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_2_reg_433 <= kernel_data_V_7;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_2_reg_433 <= kernel_data_V_6;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_2_reg_433 <= ap_phi_reg_pp0_iter0_phi_ln76_2_reg_433;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_3_reg_444 <= kernel_data_V_2;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_3_reg_444 <= kernel_data_V_1;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_3_reg_444 <= kernel_data_V_0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_3_reg_444 <= ap_phi_reg_pp0_iter0_phi_ln76_3_reg_444;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_4_reg_455 <= kernel_data_V_5;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_4_reg_455 <= kernel_data_V_4;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_4_reg_455 <= kernel_data_V_3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_4_reg_455 <= ap_phi_reg_pp0_iter0_phi_ln76_4_reg_455;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_5_reg_466 <= kernel_data_V_8;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_5_reg_466 <= kernel_data_V_7;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_5_reg_466 <= kernel_data_V_6;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_5_reg_466 <= ap_phi_reg_pp0_iter0_phi_ln76_5_reg_466;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_6_reg_477 <= kernel_data_V_2;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_6_reg_477 <= kernel_data_V_1;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_6_reg_477 <= kernel_data_V_0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_6_reg_477 <= ap_phi_reg_pp0_iter0_phi_ln76_6_reg_477;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_7_reg_488 <= kernel_data_V_5;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_7_reg_488 <= kernel_data_V_4;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_7_reg_488 <= kernel_data_V_3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_7_reg_488 <= ap_phi_reg_pp0_iter0_phi_ln76_7_reg_488;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_8_reg_499 <= kernel_data_V_8;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_8_reg_499 <= kernel_data_V_7;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_8_reg_499 <= kernel_data_V_6;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_8_reg_499 <= ap_phi_reg_pp0_iter0_phi_ln76_8_reg_499;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_9_reg_510 <= kernel_data_V_2;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_9_reg_510 <= kernel_data_V_1;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_9_reg_510 <= kernel_data_V_0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_9_reg_510 <= ap_phi_reg_pp0_iter0_phi_ln76_9_reg_510;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0) & ~(ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln76_reg_411 <= kernel_data_V_2;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_reg_411 <= kernel_data_V_1;
        end else if ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd0)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_reg_411 <= kernel_data_V_0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln76_reg_411 <= ap_phi_reg_pp0_iter0_phi_ln76_reg_411;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((io_acc_block_signal_op423 == 1'b0) & (1'd1 == and_ln272_2_reg_2341)) & (icmp_ln78_fu_2135_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        indvar_flatten23_reg_387 <= add_ln78_reg_2345;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten23_reg_387 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_483)) begin
        if ((icmp_ln293_fu_2048_p2 == 1'd1)) begin
            pX <= 32'd0;
        end else if ((icmp_ln293_fu_2048_p2 == 1'd0)) begin
            pX <= add_ln306_fu_2053_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_611)) begin
        if ((icmp_ln297_fu_2094_p2 == 1'd1)) begin
            pY <= 32'd0;
        end else if ((icmp_ln297_fu_2094_p2 == 1'd0)) begin
            pY <= add_ln301_fu_2099_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_483)) begin
        if ((icmp_ln293_fu_2048_p2 == 1'd1)) begin
            sX <= 32'd0;
        end else if ((icmp_ln293_fu_2048_p2 == 1'd0)) begin
            sX <= select_ln308_fu_2069_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_2720_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_data_0_V_820_reg_675 <= acc_0_V_fu_1972_p2;
    end else if (((data_V_data_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2) & (1'd1 == and_ln272_2_fu_981_p2))) begin
        tmp_data_0_V_820_reg_675 <= 16'd143;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_2720_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_data_1_V_418_reg_686 <= acc_1_V_fu_1982_p2;
    end else if (((data_V_data_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2) & (1'd1 == and_ln272_2_fu_981_p2))) begin
        tmp_data_1_V_418_reg_686 <= 16'd146;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_2720_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_data_2_V_416_reg_697 <= acc_2_V_fu_1992_p2;
    end else if (((data_V_data_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2) & (1'd1 == and_ln272_2_fu_981_p2))) begin
        tmp_data_2_V_416_reg_697 <= 16'd3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_2720_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_data_3_V_414_reg_708 <= acc_3_V_fu_2002_p2;
    end else if (((data_V_data_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2) & (1'd1 == and_ln272_2_fu_981_p2))) begin
        tmp_data_3_V_414_reg_708 <= 16'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_2720_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_data_4_V_412_reg_719 <= acc_4_V_fu_2012_p2;
    end else if (((data_V_data_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2) & (1'd1 == and_ln272_2_fu_981_p2))) begin
        tmp_data_4_V_412_reg_719 <= 16'd142;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_2720_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_data_5_V_410_reg_730 <= acc_5_V_fu_2022_p2;
    end else if (((data_V_data_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2) & (1'd1 == and_ln272_2_fu_981_p2))) begin
        tmp_data_5_V_410_reg_730 <= 16'd65450;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_2720_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_data_6_V_48_reg_741 <= acc_6_V_fu_2032_p2;
    end else if (((data_V_data_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2) & (1'd1 == and_ln272_2_fu_981_p2))) begin
        tmp_data_6_V_48_reg_741 <= 16'd65445;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_2720_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_data_7_V_46_reg_752 <= acc_7_V_fu_2042_p2;
    end else if (((data_V_data_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2) & (1'd1 == and_ln272_2_fu_981_p2))) begin
        tmp_data_7_V_46_reg_752 <= 16'd45;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_2720 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w_index22_reg_399 <= w_index_reg_2350;
    end else if (((data_V_data_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2) & (1'd1 == and_ln272_2_fu_981_p2))) begin
        w_index22_reg_399 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_0_V_reg_2804 <= acc_0_V_fu_1972_p2;
        acc_1_V_reg_2810 <= acc_1_V_fu_1982_p2;
        acc_2_V_reg_2816 <= acc_2_V_fu_1992_p2;
        acc_3_V_reg_2822 <= acc_3_V_fu_2002_p2;
        acc_4_V_reg_2828 <= acc_4_V_fu_2012_p2;
        acc_5_V_reg_2834 <= acc_5_V_fu_2022_p2;
        acc_6_V_reg_2840 <= acc_6_V_fu_2032_p2;
        acc_7_V_reg_2846 <= acc_7_V_fu_2042_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln703_1026_reg_2739 <= add_ln703_1026_fu_1436_p2;
        add_ln703_1029_reg_2749 <= add_ln703_1029_fu_1523_p2;
        add_ln703_1032_reg_2759 <= add_ln703_1032_fu_1610_p2;
        add_ln703_1035_reg_2769 <= add_ln703_1035_fu_1697_p2;
        add_ln703_1038_reg_2779 <= add_ln703_1038_fu_1784_p2;
        add_ln703_1041_reg_2789 <= add_ln703_1041_fu_1871_p2;
        add_ln703_1044_reg_2799 <= add_ln703_1044_fu_1962_p2;
        add_ln703_reg_2729 <= add_ln703_fu_1349_p2;
        icmp_ln64_reg_2720 <= icmp_ln64_fu_1268_p2;
        icmp_ln64_reg_2720_pp0_iter1_reg <= icmp_ln64_reg_2720;
        trunc_ln708_1024_reg_2734 <= {{mul_ln1118_1026_fu_2162_p2[25:10]}};
        trunc_ln708_1027_reg_2744 <= {{mul_ln1118_1029_fu_2183_p2[25:10]}};
        trunc_ln708_1030_reg_2754 <= {{mul_ln1118_1032_fu_2204_p2[25:10]}};
        trunc_ln708_1033_reg_2764 <= {{mul_ln1118_1035_fu_2225_p2[25:10]}};
        trunc_ln708_1036_reg_2774 <= {{mul_ln1118_1038_fu_2246_p2[25:10]}};
        trunc_ln708_1039_reg_2784 <= {{mul_ln1118_1041_fu_2267_p2[25:10]}};
        trunc_ln708_1042_reg_2794 <= {{mul_ln1118_1044_fu_2288_p2[25:10]}};
        trunc_ln_reg_2724 <= {{mul_ln1118_fu_2141_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((data_V_data_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        add_ln78_reg_2345 <= add_ln78_fu_987_p2;
        and_ln272_2_reg_2341 <= and_ln272_2_fu_981_p2;
        icmp_ln272_1_reg_2324 <= icmp_ln272_1_fu_923_p2;
        icmp_ln272_reg_2314 <= icmp_ln272_fu_913_p2;
        kernel_data_V_0 <= call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_0;
        kernel_data_V_1 <= call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_3;
        kernel_data_V_2 <= call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_4;
        kernel_data_V_3 <= call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_1;
        kernel_data_V_4 <= call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_5;
        kernel_data_V_5 <= call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_6;
        kernel_data_V_6 <= call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_2;
        kernel_data_V_7 <= call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_7;
        kernel_data_V_8 <= call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_return_8;
        pX_load_reg_2335 <= pX;
        pY_load_reg_2329 <= pY;
        sX_load_reg_2309 <= sX;
        sY_load_reg_2319 <= sY;
    end
end

always @ (posedge ap_clk) begin
    if ((~((io_acc_block_signal_op423 == 1'b0) & (1'd1 == and_ln272_2_reg_2341)) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln293_fu_2048_p2 == 1'd1))) begin
        sY <= ap_phi_mux_storemerge_i_i_phi_fu_766_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w_index_reg_2350 <= w_index_fu_993_p2;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op423 == 1'b0) & (1'd1 == and_ln272_2_reg_2341)) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln78_fu_2135_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln293_fu_2048_p2 == 1'd1))) begin
        if ((icmp_ln297_fu_2094_p2 == 1'd1)) begin
            ap_phi_mux_storemerge_i_i_phi_fu_766_p4 = 32'd0;
        end else if ((icmp_ln297_fu_2094_p2 == 1'd0)) begin
            ap_phi_mux_storemerge_i_i_phi_fu_766_p4 = select_ln303_fu_2115_p3;
        end else begin
            ap_phi_mux_storemerge_i_i_phi_fu_766_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_storemerge_i_i_phi_fu_766_p4 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln64_reg_2720 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_w_index22_phi_fu_403_p4 = w_index_reg_2350;
    end else begin
        ap_phi_mux_w_index22_phi_fu_403_p4 = w_index22_reg_399;
    end
end

always @ (*) begin
    if (((data_V_data_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_start = 1'b1;
    end else begin
        call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_773_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        data_V_data_V_blk_n = data_V_data_V_empty_n;
    end else begin
        data_V_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((data_V_data_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_V_data_V_read = 1'b1;
    end else begin
        data_V_data_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op423 == 1'b0) & (1'd1 == and_ln272_2_reg_2341)) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln78_fu_2135_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln272_2_reg_2341))) begin
        res_V_data_0_V_blk_n = res_V_data_0_V_full_n;
    end else begin
        res_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op423 == 1'b0) & (1'd1 == and_ln272_2_reg_2341)) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln272_2_reg_2341))) begin
        res_V_data_0_V_write = 1'b1;
    end else begin
        res_V_data_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln272_2_reg_2341))) begin
        res_V_data_1_V_blk_n = res_V_data_1_V_full_n;
    end else begin
        res_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op423 == 1'b0) & (1'd1 == and_ln272_2_reg_2341)) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln272_2_reg_2341))) begin
        res_V_data_1_V_write = 1'b1;
    end else begin
        res_V_data_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln272_2_reg_2341))) begin
        res_V_data_2_V_blk_n = res_V_data_2_V_full_n;
    end else begin
        res_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op423 == 1'b0) & (1'd1 == and_ln272_2_reg_2341)) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln272_2_reg_2341))) begin
        res_V_data_2_V_write = 1'b1;
    end else begin
        res_V_data_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln272_2_reg_2341))) begin
        res_V_data_3_V_blk_n = res_V_data_3_V_full_n;
    end else begin
        res_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op423 == 1'b0) & (1'd1 == and_ln272_2_reg_2341)) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln272_2_reg_2341))) begin
        res_V_data_3_V_write = 1'b1;
    end else begin
        res_V_data_3_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln272_2_reg_2341))) begin
        res_V_data_4_V_blk_n = res_V_data_4_V_full_n;
    end else begin
        res_V_data_4_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op423 == 1'b0) & (1'd1 == and_ln272_2_reg_2341)) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln272_2_reg_2341))) begin
        res_V_data_4_V_write = 1'b1;
    end else begin
        res_V_data_4_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln272_2_reg_2341))) begin
        res_V_data_5_V_blk_n = res_V_data_5_V_full_n;
    end else begin
        res_V_data_5_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op423 == 1'b0) & (1'd1 == and_ln272_2_reg_2341)) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln272_2_reg_2341))) begin
        res_V_data_5_V_write = 1'b1;
    end else begin
        res_V_data_5_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln272_2_reg_2341))) begin
        res_V_data_6_V_blk_n = res_V_data_6_V_full_n;
    end else begin
        res_V_data_6_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op423 == 1'b0) & (1'd1 == and_ln272_2_reg_2341)) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln272_2_reg_2341))) begin
        res_V_data_6_V_write = 1'b1;
    end else begin
        res_V_data_6_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln272_2_reg_2341))) begin
        res_V_data_7_V_blk_n = res_V_data_7_V_full_n;
    end else begin
        res_V_data_7_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((io_acc_block_signal_op423 == 1'b0) & (1'd1 == and_ln272_2_reg_2341)) & (1'b1 == ap_CS_fsm_state6) & (1'd1 == and_ln272_2_reg_2341))) begin
        res_V_data_7_V_write = 1'b1;
    end else begin
        res_V_data_7_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_V_ce0 = 1'b1;
    end else begin
        w2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((data_V_data_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2) & (1'd1 == and_ln272_2_fu_981_p2))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((data_V_data_V_empty_n == 1'b1) & (1'd0 == and_ln272_2_fu_981_p2) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            if ((~((io_acc_block_signal_op423 == 1'b0) & (1'd1 == and_ln272_2_reg_2341)) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln78_fu_2135_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((io_acc_block_signal_op423 == 1'b0) & (1'd1 == and_ln272_2_reg_2341)) & (icmp_ln78_fu_2135_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_0_V_fu_1972_p2 = (tmp_data_0_V_820_reg_675 + add_ln703_1024_fu_1968_p2);

assign acc_1_V_fu_1982_p2 = (tmp_data_1_V_418_reg_686 + add_ln703_1027_fu_1978_p2);

assign acc_2_V_fu_1992_p2 = (tmp_data_2_V_416_reg_697 + add_ln703_1030_fu_1988_p2);

assign acc_3_V_fu_2002_p2 = (tmp_data_3_V_414_reg_708 + add_ln703_1033_fu_1998_p2);

assign acc_4_V_fu_2012_p2 = (tmp_data_4_V_412_reg_719 + add_ln703_1036_fu_2008_p2);

assign acc_5_V_fu_2022_p2 = (tmp_data_5_V_410_reg_730 + add_ln703_1039_fu_2018_p2);

assign acc_6_V_fu_2032_p2 = (tmp_data_6_V_48_reg_741 + add_ln703_1042_fu_2028_p2);

assign acc_7_V_fu_2042_p2 = (tmp_data_7_V_46_reg_752 + add_ln703_1045_fu_2038_p2);

assign add_ln301_fu_2099_p2 = (pY_load_reg_2329 + 32'd1);

assign add_ln303_fu_2110_p2 = (sY_load_reg_2319 + 32'd1);

assign add_ln306_fu_2053_p2 = (pX_load_reg_2335 + 32'd1);

assign add_ln308_fu_2064_p2 = (sX_load_reg_2309 + 32'd1);

assign add_ln703_1024_fu_1968_p2 = (add_ln703_reg_2729 + trunc_ln_reg_2724);

assign add_ln703_1026_fu_1436_p2 = (trunc_ln708_1025_fu_1400_p4 + trunc_ln708_1026_fu_1427_p4);

assign add_ln703_1027_fu_1978_p2 = (add_ln703_1026_reg_2739 + trunc_ln708_1024_reg_2734);

assign add_ln703_1029_fu_1523_p2 = (trunc_ln708_1028_fu_1487_p4 + trunc_ln708_1029_fu_1514_p4);

assign add_ln703_1030_fu_1988_p2 = (add_ln703_1029_reg_2749 + trunc_ln708_1027_reg_2744);

assign add_ln703_1032_fu_1610_p2 = (trunc_ln708_1031_fu_1574_p4 + trunc_ln708_1032_fu_1601_p4);

assign add_ln703_1033_fu_1998_p2 = (add_ln703_1032_reg_2759 + trunc_ln708_1030_reg_2754);

assign add_ln703_1035_fu_1697_p2 = (trunc_ln708_1034_fu_1661_p4 + trunc_ln708_1035_fu_1688_p4);

assign add_ln703_1036_fu_2008_p2 = (add_ln703_1035_reg_2769 + trunc_ln708_1033_reg_2764);

assign add_ln703_1038_fu_1784_p2 = (trunc_ln708_1037_fu_1748_p4 + trunc_ln708_1038_fu_1775_p4);

assign add_ln703_1039_fu_2018_p2 = (add_ln703_1038_reg_2779 + trunc_ln708_1036_reg_2774);

assign add_ln703_1041_fu_1871_p2 = (trunc_ln708_1040_fu_1835_p4 + trunc_ln708_1041_fu_1862_p4);

assign add_ln703_1042_fu_2028_p2 = (add_ln703_1041_reg_2789 + trunc_ln708_1039_reg_2784);

assign add_ln703_1044_fu_1962_p2 = ($signed(trunc_ln708_1043_fu_1922_p4) + $signed(sext_ln708_fu_1958_p1));

assign add_ln703_1045_fu_2038_p2 = (add_ln703_1044_reg_2799 + trunc_ln708_1042_reg_2794);

assign add_ln703_fu_1349_p2 = (trunc_ln708_s_fu_1313_p4 + trunc_ln708_1023_fu_1340_p4);

assign add_ln78_fu_987_p2 = (indvar_flatten23_reg_387 + 7'd1);

assign and_ln272_1_fu_975_p2 = (icmp_ln272_3_fu_963_p2 & icmp_ln272_2_fu_943_p2);

assign and_ln272_2_fu_981_p2 = (and_ln272_fu_969_p2 & and_ln272_1_fu_975_p2);

assign and_ln272_fu_969_p2 = (icmp_ln272_fu_913_p2 & icmp_ln272_1_fu_923_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6 = ((io_acc_block_signal_op423 == 1'b0) & (1'd1 == and_ln272_2_reg_2341));
end

always @ (*) begin
    ap_condition_223 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_483 = (~((io_acc_block_signal_op423 == 1'b0) & (1'd1 == and_ln272_2_reg_2341)) & (1'b1 == ap_CS_fsm_state6));
end

always @ (*) begin
    ap_condition_611 = (~((io_acc_block_signal_op423 == 1'b0) & (1'd1 == and_ln272_2_reg_2341)) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln293_fu_2048_p2 == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_phi_ln76_10_reg_521 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_11_reg_532 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_12_reg_543 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_13_reg_554 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_14_reg_565 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_15_reg_576 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_16_reg_587 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_17_reg_598 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_18_reg_609 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_19_reg_620 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_1_reg_422 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_20_reg_631 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_21_reg_642 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_22_reg_653 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_23_reg_664 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_2_reg_433 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_3_reg_444 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_4_reg_455 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_5_reg_466 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_6_reg_477 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_7_reg_488 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_8_reg_499 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_9_reg_510 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln76_reg_411 = 'bx;

assign ap_ready = internal_ap_ready;

assign icmp_ln272_1_fu_923_p2 = ((sY == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln272_2_fu_943_p2 = (($signed(tmp_fu_933_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln272_3_fu_963_p2 = (($signed(tmp_1_fu_953_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln272_fu_913_p2 = ((sX == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln293_fu_2048_p2 = ((pX_load_reg_2335 == 32'd8) ? 1'b1 : 1'b0);

assign icmp_ln297_fu_2094_p2 = ((pY_load_reg_2329 == 32'd8) ? 1'b1 : 1'b0);

assign icmp_ln64_fu_1268_p2 = ((ap_phi_mux_w_index22_phi_fu_403_p4 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln78_fu_2135_p2 = ((indvar_flatten23_reg_387 == 7'd80) ? 1'b1 : 1'b0);

assign io_acc_block_signal_op423 = (res_V_data_7_V_full_n & res_V_data_6_V_full_n & res_V_data_5_V_full_n & res_V_data_4_V_full_n & res_V_data_3_V_full_n & res_V_data_2_V_full_n & res_V_data_1_V_full_n & res_V_data_0_V_full_n);

assign res_V_data_0_V_din = acc_0_V_reg_2804;

assign res_V_data_1_V_din = acc_1_V_reg_2810;

assign res_V_data_2_V_din = acc_2_V_reg_2816;

assign res_V_data_3_V_din = acc_3_V_reg_2822;

assign res_V_data_4_V_din = acc_4_V_reg_2828;

assign res_V_data_5_V_din = acc_5_V_reg_2834;

assign res_V_data_6_V_din = acc_6_V_reg_2840;

assign res_V_data_7_V_din = acc_7_V_reg_2846;

assign select_ln303_fu_2115_p3 = ((icmp_ln272_1_reg_2324[0:0] === 1'b1) ? 32'd1 : add_ln303_fu_2110_p2);

assign select_ln308_fu_2069_p3 = ((icmp_ln272_reg_2314[0:0] === 1'b1) ? 32'd1 : add_ln308_fu_2064_p2);

assign sext_ln708_fu_1958_p1 = $signed(trunc_ln708_1044_fu_1949_p4);

assign start_out = real_start;

assign tmp_1023_fu_1295_p4 = {{w2_V_q0[31:16]}};

assign tmp_1024_fu_1322_p4 = {{w2_V_q0[47:32]}};

assign tmp_1025_fu_1355_p4 = {{w2_V_q0[63:48]}};

assign tmp_1026_fu_1382_p4 = {{w2_V_q0[79:64]}};

assign tmp_1027_fu_1409_p4 = {{w2_V_q0[95:80]}};

assign tmp_1028_fu_1442_p4 = {{w2_V_q0[111:96]}};

assign tmp_1029_fu_1469_p4 = {{w2_V_q0[127:112]}};

assign tmp_1030_fu_1496_p4 = {{w2_V_q0[143:128]}};

assign tmp_1031_fu_1529_p4 = {{w2_V_q0[159:144]}};

assign tmp_1032_fu_1556_p4 = {{w2_V_q0[175:160]}};

assign tmp_1033_fu_1583_p4 = {{w2_V_q0[191:176]}};

assign tmp_1034_fu_1616_p4 = {{w2_V_q0[207:192]}};

assign tmp_1035_fu_1643_p4 = {{w2_V_q0[223:208]}};

assign tmp_1036_fu_1670_p4 = {{w2_V_q0[239:224]}};

assign tmp_1037_fu_1703_p4 = {{w2_V_q0[255:240]}};

assign tmp_1038_fu_1730_p4 = {{w2_V_q0[271:256]}};

assign tmp_1039_fu_1757_p4 = {{w2_V_q0[287:272]}};

assign tmp_1040_fu_1790_p4 = {{w2_V_q0[303:288]}};

assign tmp_1041_fu_1817_p4 = {{w2_V_q0[319:304]}};

assign tmp_1042_fu_1844_p4 = {{w2_V_q0[335:320]}};

assign tmp_1043_fu_1877_p4 = {{w2_V_q0[351:336]}};

assign tmp_1044_fu_1904_p4 = {{w2_V_q0[367:352]}};

assign tmp_1045_fu_1931_p4 = {{w2_V_q0[376:368]}};

assign tmp_1_fu_953_p4 = {{pX[31:1]}};

assign tmp_fu_933_p4 = {{pY[31:1]}};

assign trunc_ln708_1023_fu_1340_p4 = {{mul_ln1118_1025_fu_2155_p2[25:10]}};

assign trunc_ln708_1025_fu_1400_p4 = {{mul_ln1118_1027_fu_2169_p2[25:10]}};

assign trunc_ln708_1026_fu_1427_p4 = {{mul_ln1118_1028_fu_2176_p2[25:10]}};

assign trunc_ln708_1028_fu_1487_p4 = {{mul_ln1118_1030_fu_2190_p2[25:10]}};

assign trunc_ln708_1029_fu_1514_p4 = {{mul_ln1118_1031_fu_2197_p2[25:10]}};

assign trunc_ln708_1031_fu_1574_p4 = {{mul_ln1118_1033_fu_2211_p2[25:10]}};

assign trunc_ln708_1032_fu_1601_p4 = {{mul_ln1118_1034_fu_2218_p2[25:10]}};

assign trunc_ln708_1034_fu_1661_p4 = {{mul_ln1118_1036_fu_2232_p2[25:10]}};

assign trunc_ln708_1035_fu_1688_p4 = {{mul_ln1118_1037_fu_2239_p2[25:10]}};

assign trunc_ln708_1037_fu_1748_p4 = {{mul_ln1118_1039_fu_2253_p2[25:10]}};

assign trunc_ln708_1038_fu_1775_p4 = {{mul_ln1118_1040_fu_2260_p2[25:10]}};

assign trunc_ln708_1040_fu_1835_p4 = {{mul_ln1118_1042_fu_2274_p2[25:10]}};

assign trunc_ln708_1041_fu_1862_p4 = {{mul_ln1118_1043_fu_2281_p2[25:10]}};

assign trunc_ln708_1043_fu_1922_p4 = {{mul_ln1118_1045_fu_2295_p2[25:10]}};

assign trunc_ln708_1044_fu_1949_p4 = {{mul_ln1118_1046_fu_2302_p2[24:10]}};

assign trunc_ln708_s_fu_1313_p4 = {{mul_ln1118_1024_fu_2148_p2[25:10]}};

assign trunc_ln76_fu_1274_p1 = w2_V_q0[15:0];

assign w2_V_address0 = zext_ln76_fu_1003_p1;

assign w_index_fu_993_p2 = (ap_phi_mux_w_index22_phi_fu_403_p4 + 2'd1);

assign zext_ln76_fu_1003_p1 = ap_phi_mux_w_index22_phi_fu_403_p4;

endmodule //conv_2d_cl_array_array_ap_fixed_8u_config2_s
