// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_array_array_ap_fixed_16_6_5_3_0_16u_config5_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        data_stream_V_data_0_V_dout,
        data_stream_V_data_0_V_empty_n,
        data_stream_V_data_0_V_read,
        data_stream_V_data_1_V_dout,
        data_stream_V_data_1_V_empty_n,
        data_stream_V_data_1_V_read,
        data_stream_V_data_2_V_dout,
        data_stream_V_data_2_V_empty_n,
        data_stream_V_data_2_V_read,
        data_stream_V_data_3_V_dout,
        data_stream_V_data_3_V_empty_n,
        data_stream_V_data_3_V_read,
        data_stream_V_data_4_V_dout,
        data_stream_V_data_4_V_empty_n,
        data_stream_V_data_4_V_read,
        data_stream_V_data_5_V_dout,
        data_stream_V_data_5_V_empty_n,
        data_stream_V_data_5_V_read,
        data_stream_V_data_6_V_dout,
        data_stream_V_data_6_V_empty_n,
        data_stream_V_data_6_V_read,
        data_stream_V_data_7_V_dout,
        data_stream_V_data_7_V_empty_n,
        data_stream_V_data_7_V_read,
        res_stream_V_data_0_V_din,
        res_stream_V_data_0_V_full_n,
        res_stream_V_data_0_V_write,
        res_stream_V_data_1_V_din,
        res_stream_V_data_1_V_full_n,
        res_stream_V_data_1_V_write,
        res_stream_V_data_2_V_din,
        res_stream_V_data_2_V_full_n,
        res_stream_V_data_2_V_write,
        res_stream_V_data_3_V_din,
        res_stream_V_data_3_V_full_n,
        res_stream_V_data_3_V_write,
        res_stream_V_data_4_V_din,
        res_stream_V_data_4_V_full_n,
        res_stream_V_data_4_V_write,
        res_stream_V_data_5_V_din,
        res_stream_V_data_5_V_full_n,
        res_stream_V_data_5_V_write,
        res_stream_V_data_6_V_din,
        res_stream_V_data_6_V_full_n,
        res_stream_V_data_6_V_write,
        res_stream_V_data_7_V_din,
        res_stream_V_data_7_V_full_n,
        res_stream_V_data_7_V_write,
        res_stream_V_data_8_V_din,
        res_stream_V_data_8_V_full_n,
        res_stream_V_data_8_V_write,
        res_stream_V_data_9_V_din,
        res_stream_V_data_9_V_full_n,
        res_stream_V_data_9_V_write,
        res_stream_V_data_10_V_din,
        res_stream_V_data_10_V_full_n,
        res_stream_V_data_10_V_write,
        res_stream_V_data_11_V_din,
        res_stream_V_data_11_V_full_n,
        res_stream_V_data_11_V_write,
        res_stream_V_data_12_V_din,
        res_stream_V_data_12_V_full_n,
        res_stream_V_data_12_V_write,
        res_stream_V_data_13_V_din,
        res_stream_V_data_13_V_full_n,
        res_stream_V_data_13_V_write,
        res_stream_V_data_14_V_din,
        res_stream_V_data_14_V_full_n,
        res_stream_V_data_14_V_write,
        res_stream_V_data_15_V_din,
        res_stream_V_data_15_V_full_n,
        res_stream_V_data_15_V_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_pp0_stage0 = 5'd2;
parameter    ap_ST_fsm_state4 = 5'd4;
parameter    ap_ST_fsm_state5 = 5'd8;
parameter    ap_ST_fsm_state6 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [15:0] data_stream_V_data_0_V_dout;
input   data_stream_V_data_0_V_empty_n;
output   data_stream_V_data_0_V_read;
input  [15:0] data_stream_V_data_1_V_dout;
input   data_stream_V_data_1_V_empty_n;
output   data_stream_V_data_1_V_read;
input  [15:0] data_stream_V_data_2_V_dout;
input   data_stream_V_data_2_V_empty_n;
output   data_stream_V_data_2_V_read;
input  [15:0] data_stream_V_data_3_V_dout;
input   data_stream_V_data_3_V_empty_n;
output   data_stream_V_data_3_V_read;
input  [15:0] data_stream_V_data_4_V_dout;
input   data_stream_V_data_4_V_empty_n;
output   data_stream_V_data_4_V_read;
input  [15:0] data_stream_V_data_5_V_dout;
input   data_stream_V_data_5_V_empty_n;
output   data_stream_V_data_5_V_read;
input  [15:0] data_stream_V_data_6_V_dout;
input   data_stream_V_data_6_V_empty_n;
output   data_stream_V_data_6_V_read;
input  [15:0] data_stream_V_data_7_V_dout;
input   data_stream_V_data_7_V_empty_n;
output   data_stream_V_data_7_V_read;
output  [15:0] res_stream_V_data_0_V_din;
input   res_stream_V_data_0_V_full_n;
output   res_stream_V_data_0_V_write;
output  [15:0] res_stream_V_data_1_V_din;
input   res_stream_V_data_1_V_full_n;
output   res_stream_V_data_1_V_write;
output  [15:0] res_stream_V_data_2_V_din;
input   res_stream_V_data_2_V_full_n;
output   res_stream_V_data_2_V_write;
output  [15:0] res_stream_V_data_3_V_din;
input   res_stream_V_data_3_V_full_n;
output   res_stream_V_data_3_V_write;
output  [15:0] res_stream_V_data_4_V_din;
input   res_stream_V_data_4_V_full_n;
output   res_stream_V_data_4_V_write;
output  [15:0] res_stream_V_data_5_V_din;
input   res_stream_V_data_5_V_full_n;
output   res_stream_V_data_5_V_write;
output  [15:0] res_stream_V_data_6_V_din;
input   res_stream_V_data_6_V_full_n;
output   res_stream_V_data_6_V_write;
output  [15:0] res_stream_V_data_7_V_din;
input   res_stream_V_data_7_V_full_n;
output   res_stream_V_data_7_V_write;
output  [15:0] res_stream_V_data_8_V_din;
input   res_stream_V_data_8_V_full_n;
output   res_stream_V_data_8_V_write;
output  [15:0] res_stream_V_data_9_V_din;
input   res_stream_V_data_9_V_full_n;
output   res_stream_V_data_9_V_write;
output  [15:0] res_stream_V_data_10_V_din;
input   res_stream_V_data_10_V_full_n;
output   res_stream_V_data_10_V_write;
output  [15:0] res_stream_V_data_11_V_din;
input   res_stream_V_data_11_V_full_n;
output   res_stream_V_data_11_V_write;
output  [15:0] res_stream_V_data_12_V_din;
input   res_stream_V_data_12_V_full_n;
output   res_stream_V_data_12_V_write;
output  [15:0] res_stream_V_data_13_V_din;
input   res_stream_V_data_13_V_full_n;
output   res_stream_V_data_13_V_write;
output  [15:0] res_stream_V_data_14_V_din;
input   res_stream_V_data_14_V_full_n;
output   res_stream_V_data_14_V_write;
output  [15:0] res_stream_V_data_15_V_din;
input   res_stream_V_data_15_V_full_n;
output   res_stream_V_data_15_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg data_stream_V_data_0_V_read;
reg data_stream_V_data_1_V_read;
reg data_stream_V_data_2_V_read;
reg data_stream_V_data_3_V_read;
reg data_stream_V_data_4_V_read;
reg data_stream_V_data_5_V_read;
reg data_stream_V_data_6_V_read;
reg data_stream_V_data_7_V_read;
reg res_stream_V_data_0_V_write;
reg res_stream_V_data_1_V_write;
reg res_stream_V_data_2_V_write;
reg res_stream_V_data_3_V_write;
reg res_stream_V_data_4_V_write;
reg res_stream_V_data_5_V_write;
reg res_stream_V_data_6_V_write;
reg res_stream_V_data_7_V_write;
reg res_stream_V_data_8_V_write;
reg res_stream_V_data_9_V_write;
reg res_stream_V_data_10_V_write;
reg res_stream_V_data_11_V_write;
reg res_stream_V_data_12_V_write;
reg res_stream_V_data_13_V_write;
reg res_stream_V_data_14_V_write;
reg res_stream_V_data_15_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    data_stream_V_data_0_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg    data_stream_V_data_1_V_blk_n;
reg    data_stream_V_data_2_V_blk_n;
reg    data_stream_V_data_3_V_blk_n;
reg    data_stream_V_data_4_V_blk_n;
reg    data_stream_V_data_5_V_blk_n;
reg    data_stream_V_data_6_V_blk_n;
reg    data_stream_V_data_7_V_blk_n;
reg    res_stream_V_data_0_V_blk_n;
wire    ap_CS_fsm_state6;
reg    res_stream_V_data_1_V_blk_n;
reg    res_stream_V_data_2_V_blk_n;
reg    res_stream_V_data_3_V_blk_n;
reg    res_stream_V_data_4_V_blk_n;
reg    res_stream_V_data_5_V_blk_n;
reg    res_stream_V_data_6_V_blk_n;
reg    res_stream_V_data_7_V_blk_n;
reg    res_stream_V_data_8_V_blk_n;
reg    res_stream_V_data_9_V_blk_n;
reg    res_stream_V_data_10_V_blk_n;
reg    res_stream_V_data_11_V_blk_n;
reg    res_stream_V_data_12_V_blk_n;
reg    res_stream_V_data_13_V_blk_n;
reg    res_stream_V_data_14_V_blk_n;
reg    res_stream_V_data_15_V_blk_n;
reg   [4:0] i_in_0_reg_998;
wire   [0:0] icmp_ln41_fu_1143_p2;
wire    ap_block_state2_pp0_stage0_iter0;
wire    io_acc_block_signal_op298;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [4:0] i_in_fu_1149_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [3:0] trunc_ln203_fu_1155_p1;
reg   [3:0] trunc_ln203_reg_3184;
wire    ap_CS_fsm_state4;
reg   [15:0] tmp_data_0_V_reg_3828;
wire    ap_CS_fsm_state5;
wire    grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_ready;
wire    grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_done;
reg   [15:0] tmp_data_1_V_reg_3833;
reg   [15:0] tmp_data_2_V_reg_3838;
reg   [15:0] tmp_data_3_V_reg_3843;
reg   [15:0] tmp_data_4_V_reg_3848;
reg   [15:0] tmp_data_5_V_reg_3853;
reg   [15:0] tmp_data_6_V_reg_3858;
reg   [15:0] tmp_data_7_V_reg_3863;
reg   [15:0] tmp_data_8_V_reg_3868;
reg   [15:0] tmp_data_9_V_reg_3873;
reg   [15:0] tmp_data_10_V_reg_3878;
reg   [15:0] tmp_data_11_V_reg_3883;
reg   [15:0] tmp_data_12_V_reg_3888;
reg   [15:0] tmp_data_13_V_reg_3893;
reg   [15:0] tmp_data_14_V_reg_3898;
reg   [15:0] tmp_data_15_V_reg_3903;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
wire    grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_start;
wire    grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_idle;
wire   [15:0] grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_0;
wire   [15:0] grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_1;
wire   [15:0] grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_2;
wire   [15:0] grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_3;
wire   [15:0] grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_4;
wire   [15:0] grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_5;
wire   [15:0] grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_6;
wire   [15:0] grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_7;
wire   [15:0] grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_8;
wire   [15:0] grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_9;
wire   [15:0] grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_10;
wire   [15:0] grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_11;
wire   [15:0] grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_12;
wire   [15:0] grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_13;
wire   [15:0] grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_14;
wire   [15:0] grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_15;
reg    grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_start_reg;
reg   [15:0] data_120_V_fu_414;
reg   [15:0] data_121_V_fu_418;
reg   [15:0] data_122_V_fu_422;
reg   [15:0] data_123_V_fu_426;
reg   [15:0] data_124_V_fu_430;
reg   [15:0] data_125_V_fu_434;
reg   [15:0] data_126_V_fu_438;
reg   [15:0] data_127_V_fu_442;
reg   [15:0] data_120_V_1_fu_446;
reg   [15:0] data_121_V_1_fu_450;
reg   [15:0] data_122_V_1_fu_454;
reg   [15:0] data_123_V_1_fu_458;
reg   [15:0] data_124_V_1_fu_462;
reg   [15:0] data_125_V_1_fu_466;
reg   [15:0] data_126_V_1_fu_470;
reg   [15:0] data_127_V_1_fu_474;
reg   [15:0] data_120_V_2_fu_478;
reg   [15:0] data_121_V_2_fu_482;
reg   [15:0] data_122_V_2_fu_486;
reg   [15:0] data_123_V_2_fu_490;
reg   [15:0] data_124_V_2_fu_494;
reg   [15:0] data_125_V_2_fu_498;
reg   [15:0] data_126_V_2_fu_502;
reg   [15:0] data_127_V_2_fu_506;
reg   [15:0] data_120_V_3_fu_510;
reg   [15:0] data_121_V_3_fu_514;
reg   [15:0] data_122_V_3_fu_518;
reg   [15:0] data_123_V_3_fu_522;
reg   [15:0] data_124_V_3_fu_526;
reg   [15:0] data_125_V_3_fu_530;
reg   [15:0] data_126_V_3_fu_534;
reg   [15:0] data_127_V_3_fu_538;
reg   [15:0] data_120_V_4_fu_542;
reg   [15:0] data_121_V_4_fu_546;
reg   [15:0] data_122_V_4_fu_550;
reg   [15:0] data_123_V_4_fu_554;
reg   [15:0] data_124_V_4_fu_558;
reg   [15:0] data_125_V_4_fu_562;
reg   [15:0] data_126_V_4_fu_566;
reg   [15:0] data_127_V_4_fu_570;
reg   [15:0] data_120_V_5_fu_574;
reg   [15:0] data_121_V_5_fu_578;
reg   [15:0] data_122_V_5_fu_582;
reg   [15:0] data_123_V_5_fu_586;
reg   [15:0] data_124_V_5_fu_590;
reg   [15:0] data_125_V_5_fu_594;
reg   [15:0] data_126_V_5_fu_598;
reg   [15:0] data_127_V_5_fu_602;
reg   [15:0] data_120_V_6_fu_606;
reg   [15:0] data_121_V_6_fu_610;
reg   [15:0] data_122_V_6_fu_614;
reg   [15:0] data_123_V_6_fu_618;
reg   [15:0] data_124_V_6_fu_622;
reg   [15:0] data_125_V_6_fu_626;
reg   [15:0] data_126_V_6_fu_630;
reg   [15:0] data_127_V_6_fu_634;
reg   [15:0] data_120_V_7_fu_638;
reg   [15:0] data_121_V_7_fu_642;
reg   [15:0] data_122_V_7_fu_646;
reg   [15:0] data_123_V_7_fu_650;
reg   [15:0] data_124_V_7_fu_654;
reg   [15:0] data_125_V_7_fu_658;
reg   [15:0] data_126_V_7_fu_662;
reg   [15:0] data_127_V_7_fu_666;
reg   [15:0] data_120_V_8_fu_670;
reg   [15:0] data_121_V_8_fu_674;
reg   [15:0] data_122_V_8_fu_678;
reg   [15:0] data_123_V_8_fu_682;
reg   [15:0] data_124_V_8_fu_686;
reg   [15:0] data_125_V_8_fu_690;
reg   [15:0] data_126_V_8_fu_694;
reg   [15:0] data_127_V_8_fu_698;
reg   [15:0] data_120_V_9_fu_702;
reg   [15:0] data_121_V_9_fu_706;
reg   [15:0] data_122_V_9_fu_710;
reg   [15:0] data_123_V_9_fu_714;
reg   [15:0] data_124_V_9_fu_718;
reg   [15:0] data_125_V_9_fu_722;
reg   [15:0] data_126_V_9_fu_726;
reg   [15:0] data_127_V_9_fu_730;
reg   [15:0] data_120_V_10_fu_734;
reg   [15:0] data_121_V_10_fu_738;
reg   [15:0] data_122_V_10_fu_742;
reg   [15:0] data_123_V_10_fu_746;
reg   [15:0] data_124_V_10_fu_750;
reg   [15:0] data_125_V_10_fu_754;
reg   [15:0] data_126_V_10_fu_758;
reg   [15:0] data_127_V_10_fu_762;
reg   [15:0] data_120_V_11_fu_766;
reg   [15:0] data_121_V_11_fu_770;
reg   [15:0] data_122_V_11_fu_774;
reg   [15:0] data_123_V_11_fu_778;
reg   [15:0] data_124_V_11_fu_782;
reg   [15:0] data_125_V_11_fu_786;
reg   [15:0] data_126_V_11_fu_790;
reg   [15:0] data_127_V_11_fu_794;
reg   [15:0] data_120_V_12_fu_798;
reg   [15:0] data_121_V_12_fu_802;
reg   [15:0] data_122_V_12_fu_806;
reg   [15:0] data_123_V_12_fu_810;
reg   [15:0] data_124_V_12_fu_814;
reg   [15:0] data_125_V_12_fu_818;
reg   [15:0] data_126_V_12_fu_822;
reg   [15:0] data_127_V_12_fu_826;
reg   [15:0] data_120_V_13_fu_830;
reg   [15:0] data_121_V_13_fu_834;
reg   [15:0] data_122_V_13_fu_838;
reg   [15:0] data_123_V_13_fu_842;
reg   [15:0] data_124_V_13_fu_846;
reg   [15:0] data_125_V_13_fu_850;
reg   [15:0] data_126_V_13_fu_854;
reg   [15:0] data_127_V_13_fu_858;
reg   [15:0] data_120_V_14_fu_862;
reg   [15:0] data_121_V_14_fu_866;
reg   [15:0] data_122_V_14_fu_870;
reg   [15:0] data_123_V_14_fu_874;
reg   [15:0] data_124_V_14_fu_878;
reg   [15:0] data_125_V_14_fu_882;
reg   [15:0] data_126_V_14_fu_886;
reg   [15:0] data_127_V_14_fu_890;
reg   [15:0] data_120_V_15_fu_894;
reg   [15:0] data_121_V_15_fu_898;
reg   [15:0] data_122_V_15_fu_902;
reg   [15:0] data_123_V_15_fu_906;
reg   [15:0] data_124_V_15_fu_910;
reg   [15:0] data_125_V_15_fu_914;
reg   [15:0] data_126_V_15_fu_918;
reg   [15:0] data_127_V_15_fu_922;
wire    io_acc_block_signal_op591;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_start_reg = 1'b0;
end

dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_start),
    .ap_done(grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_done),
    .ap_idle(grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_idle),
    .ap_ready(grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_ready),
    .data_0_V_read(data_120_V_fu_414),
    .data_1_V_read(data_121_V_fu_418),
    .data_2_V_read(data_122_V_fu_422),
    .data_3_V_read(data_123_V_fu_426),
    .data_4_V_read(data_124_V_fu_430),
    .data_5_V_read(data_125_V_fu_434),
    .data_6_V_read(data_126_V_fu_438),
    .data_7_V_read(data_127_V_fu_442),
    .data_8_V_read(data_120_V_1_fu_446),
    .data_9_V_read(data_121_V_1_fu_450),
    .data_10_V_read(data_122_V_1_fu_454),
    .data_11_V_read(data_123_V_1_fu_458),
    .data_12_V_read(data_124_V_1_fu_462),
    .data_13_V_read(data_125_V_1_fu_466),
    .data_14_V_read(data_126_V_1_fu_470),
    .data_15_V_read(data_127_V_1_fu_474),
    .data_16_V_read(data_120_V_2_fu_478),
    .data_17_V_read(data_121_V_2_fu_482),
    .data_18_V_read(data_122_V_2_fu_486),
    .data_19_V_read(data_123_V_2_fu_490),
    .data_20_V_read(data_124_V_2_fu_494),
    .data_21_V_read(data_125_V_2_fu_498),
    .data_22_V_read(data_126_V_2_fu_502),
    .data_23_V_read(data_127_V_2_fu_506),
    .data_24_V_read(data_120_V_3_fu_510),
    .data_25_V_read(data_121_V_3_fu_514),
    .data_26_V_read(data_122_V_3_fu_518),
    .data_27_V_read(data_123_V_3_fu_522),
    .data_28_V_read(data_124_V_3_fu_526),
    .data_29_V_read(data_125_V_3_fu_530),
    .data_30_V_read(data_126_V_3_fu_534),
    .data_31_V_read(data_127_V_3_fu_538),
    .data_32_V_read(data_120_V_4_fu_542),
    .data_33_V_read(data_121_V_4_fu_546),
    .data_34_V_read(data_122_V_4_fu_550),
    .data_35_V_read(data_123_V_4_fu_554),
    .data_36_V_read(data_124_V_4_fu_558),
    .data_37_V_read(data_125_V_4_fu_562),
    .data_38_V_read(data_126_V_4_fu_566),
    .data_39_V_read(data_127_V_4_fu_570),
    .data_40_V_read(data_120_V_5_fu_574),
    .data_41_V_read(data_121_V_5_fu_578),
    .data_42_V_read(data_122_V_5_fu_582),
    .data_43_V_read(data_123_V_5_fu_586),
    .data_44_V_read(data_124_V_5_fu_590),
    .data_45_V_read(data_125_V_5_fu_594),
    .data_46_V_read(data_126_V_5_fu_598),
    .data_47_V_read(data_127_V_5_fu_602),
    .data_48_V_read(data_120_V_6_fu_606),
    .data_49_V_read(data_121_V_6_fu_610),
    .data_50_V_read(data_122_V_6_fu_614),
    .data_51_V_read(data_123_V_6_fu_618),
    .data_52_V_read(data_124_V_6_fu_622),
    .data_53_V_read(data_125_V_6_fu_626),
    .data_54_V_read(data_126_V_6_fu_630),
    .data_55_V_read(data_127_V_6_fu_634),
    .data_56_V_read(data_120_V_7_fu_638),
    .data_57_V_read(data_121_V_7_fu_642),
    .data_58_V_read(data_122_V_7_fu_646),
    .data_59_V_read(data_123_V_7_fu_650),
    .data_60_V_read(data_124_V_7_fu_654),
    .data_61_V_read(data_125_V_7_fu_658),
    .data_62_V_read(data_126_V_7_fu_662),
    .data_63_V_read(data_127_V_7_fu_666),
    .data_64_V_read(data_120_V_8_fu_670),
    .data_65_V_read(data_121_V_8_fu_674),
    .data_66_V_read(data_122_V_8_fu_678),
    .data_67_V_read(data_123_V_8_fu_682),
    .data_68_V_read(data_124_V_8_fu_686),
    .data_69_V_read(data_125_V_8_fu_690),
    .data_70_V_read(data_126_V_8_fu_694),
    .data_71_V_read(data_127_V_8_fu_698),
    .data_72_V_read(data_120_V_9_fu_702),
    .data_73_V_read(data_121_V_9_fu_706),
    .data_74_V_read(data_122_V_9_fu_710),
    .data_75_V_read(data_123_V_9_fu_714),
    .data_76_V_read(data_124_V_9_fu_718),
    .data_77_V_read(data_125_V_9_fu_722),
    .data_78_V_read(data_126_V_9_fu_726),
    .data_79_V_read(data_127_V_9_fu_730),
    .data_80_V_read(data_120_V_10_fu_734),
    .data_81_V_read(data_121_V_10_fu_738),
    .data_82_V_read(data_122_V_10_fu_742),
    .data_83_V_read(data_123_V_10_fu_746),
    .data_84_V_read(data_124_V_10_fu_750),
    .data_85_V_read(data_125_V_10_fu_754),
    .data_86_V_read(data_126_V_10_fu_758),
    .data_87_V_read(data_127_V_10_fu_762),
    .data_88_V_read(data_120_V_11_fu_766),
    .data_89_V_read(data_121_V_11_fu_770),
    .data_90_V_read(data_122_V_11_fu_774),
    .data_91_V_read(data_123_V_11_fu_778),
    .data_92_V_read(data_124_V_11_fu_782),
    .data_93_V_read(data_125_V_11_fu_786),
    .data_94_V_read(data_126_V_11_fu_790),
    .data_95_V_read(data_127_V_11_fu_794),
    .data_96_V_read(data_120_V_12_fu_798),
    .data_97_V_read(data_121_V_12_fu_802),
    .data_98_V_read(data_122_V_12_fu_806),
    .data_99_V_read(data_123_V_12_fu_810),
    .data_100_V_read(data_124_V_12_fu_814),
    .data_101_V_read(data_125_V_12_fu_818),
    .data_102_V_read(data_126_V_12_fu_822),
    .data_103_V_read(data_127_V_12_fu_826),
    .data_104_V_read(data_120_V_13_fu_830),
    .data_105_V_read(data_121_V_13_fu_834),
    .data_106_V_read(data_122_V_13_fu_838),
    .data_107_V_read(data_123_V_13_fu_842),
    .data_108_V_read(data_124_V_13_fu_846),
    .data_109_V_read(data_125_V_13_fu_850),
    .data_110_V_read(data_126_V_13_fu_854),
    .data_111_V_read(data_127_V_13_fu_858),
    .data_112_V_read(data_120_V_14_fu_862),
    .data_113_V_read(data_121_V_14_fu_866),
    .data_114_V_read(data_122_V_14_fu_870),
    .data_115_V_read(data_123_V_14_fu_874),
    .data_116_V_read(data_124_V_14_fu_878),
    .data_117_V_read(data_125_V_14_fu_882),
    .data_118_V_read(data_126_V_14_fu_886),
    .data_119_V_read(data_127_V_14_fu_890),
    .data_120_V_read(data_120_V_15_fu_894),
    .data_121_V_read(data_121_V_15_fu_898),
    .data_122_V_read(data_122_V_15_fu_902),
    .data_123_V_read(data_123_V_15_fu_906),
    .data_124_V_read(data_124_V_15_fu_910),
    .data_125_V_read(data_125_V_15_fu_914),
    .data_126_V_read(data_126_V_15_fu_918),
    .data_127_V_read(data_127_V_15_fu_922),
    .ap_return_0(grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_0),
    .ap_return_1(grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_1),
    .ap_return_2(grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_2),
    .ap_return_3(grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_3),
    .ap_return_4(grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_4),
    .ap_return_5(grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_5),
    .ap_return_6(grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_6),
    .ap_return_7(grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_7),
    .ap_return_8(grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_8),
    .ap_return_9(grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_9),
    .ap_return_10(grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_10),
    .ap_return_11(grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_11),
    .ap_return_12(grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_12),
    .ap_return_13(grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_13),
    .ap_return_14(grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_14),
    .ap_return_15(grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_15)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state6) & (io_acc_block_signal_op591 == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_start_reg <= 1'b1;
        end else if ((grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_ready == 1'b1)) begin
            grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln41_fu_1143_p2 == 1'd0))) begin
        i_in_0_reg_998 <= i_in_fu_1149_p2;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_in_0_reg_998 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln203_reg_3184 == 4'd10) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_120_V_10_fu_734 <= data_stream_V_data_0_V_dout;
        data_121_V_10_fu_738 <= data_stream_V_data_1_V_dout;
        data_122_V_10_fu_742 <= data_stream_V_data_2_V_dout;
        data_123_V_10_fu_746 <= data_stream_V_data_3_V_dout;
        data_124_V_10_fu_750 <= data_stream_V_data_4_V_dout;
        data_125_V_10_fu_754 <= data_stream_V_data_5_V_dout;
        data_126_V_10_fu_758 <= data_stream_V_data_6_V_dout;
        data_127_V_10_fu_762 <= data_stream_V_data_7_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln203_reg_3184 == 4'd11) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_120_V_11_fu_766 <= data_stream_V_data_0_V_dout;
        data_121_V_11_fu_770 <= data_stream_V_data_1_V_dout;
        data_122_V_11_fu_774 <= data_stream_V_data_2_V_dout;
        data_123_V_11_fu_778 <= data_stream_V_data_3_V_dout;
        data_124_V_11_fu_782 <= data_stream_V_data_4_V_dout;
        data_125_V_11_fu_786 <= data_stream_V_data_5_V_dout;
        data_126_V_11_fu_790 <= data_stream_V_data_6_V_dout;
        data_127_V_11_fu_794 <= data_stream_V_data_7_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln203_reg_3184 == 4'd12) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_120_V_12_fu_798 <= data_stream_V_data_0_V_dout;
        data_121_V_12_fu_802 <= data_stream_V_data_1_V_dout;
        data_122_V_12_fu_806 <= data_stream_V_data_2_V_dout;
        data_123_V_12_fu_810 <= data_stream_V_data_3_V_dout;
        data_124_V_12_fu_814 <= data_stream_V_data_4_V_dout;
        data_125_V_12_fu_818 <= data_stream_V_data_5_V_dout;
        data_126_V_12_fu_822 <= data_stream_V_data_6_V_dout;
        data_127_V_12_fu_826 <= data_stream_V_data_7_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln203_reg_3184 == 4'd13) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_120_V_13_fu_830 <= data_stream_V_data_0_V_dout;
        data_121_V_13_fu_834 <= data_stream_V_data_1_V_dout;
        data_122_V_13_fu_838 <= data_stream_V_data_2_V_dout;
        data_123_V_13_fu_842 <= data_stream_V_data_3_V_dout;
        data_124_V_13_fu_846 <= data_stream_V_data_4_V_dout;
        data_125_V_13_fu_850 <= data_stream_V_data_5_V_dout;
        data_126_V_13_fu_854 <= data_stream_V_data_6_V_dout;
        data_127_V_13_fu_858 <= data_stream_V_data_7_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln203_reg_3184 == 4'd14) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_120_V_14_fu_862 <= data_stream_V_data_0_V_dout;
        data_121_V_14_fu_866 <= data_stream_V_data_1_V_dout;
        data_122_V_14_fu_870 <= data_stream_V_data_2_V_dout;
        data_123_V_14_fu_874 <= data_stream_V_data_3_V_dout;
        data_124_V_14_fu_878 <= data_stream_V_data_4_V_dout;
        data_125_V_14_fu_882 <= data_stream_V_data_5_V_dout;
        data_126_V_14_fu_886 <= data_stream_V_data_6_V_dout;
        data_127_V_14_fu_890 <= data_stream_V_data_7_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln203_reg_3184 == 4'd15) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_120_V_15_fu_894 <= data_stream_V_data_0_V_dout;
        data_121_V_15_fu_898 <= data_stream_V_data_1_V_dout;
        data_122_V_15_fu_902 <= data_stream_V_data_2_V_dout;
        data_123_V_15_fu_906 <= data_stream_V_data_3_V_dout;
        data_124_V_15_fu_910 <= data_stream_V_data_4_V_dout;
        data_125_V_15_fu_914 <= data_stream_V_data_5_V_dout;
        data_126_V_15_fu_918 <= data_stream_V_data_6_V_dout;
        data_127_V_15_fu_922 <= data_stream_V_data_7_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln203_reg_3184 == 4'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_120_V_1_fu_446 <= data_stream_V_data_0_V_dout;
        data_121_V_1_fu_450 <= data_stream_V_data_1_V_dout;
        data_122_V_1_fu_454 <= data_stream_V_data_2_V_dout;
        data_123_V_1_fu_458 <= data_stream_V_data_3_V_dout;
        data_124_V_1_fu_462 <= data_stream_V_data_4_V_dout;
        data_125_V_1_fu_466 <= data_stream_V_data_5_V_dout;
        data_126_V_1_fu_470 <= data_stream_V_data_6_V_dout;
        data_127_V_1_fu_474 <= data_stream_V_data_7_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln203_reg_3184 == 4'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_120_V_2_fu_478 <= data_stream_V_data_0_V_dout;
        data_121_V_2_fu_482 <= data_stream_V_data_1_V_dout;
        data_122_V_2_fu_486 <= data_stream_V_data_2_V_dout;
        data_123_V_2_fu_490 <= data_stream_V_data_3_V_dout;
        data_124_V_2_fu_494 <= data_stream_V_data_4_V_dout;
        data_125_V_2_fu_498 <= data_stream_V_data_5_V_dout;
        data_126_V_2_fu_502 <= data_stream_V_data_6_V_dout;
        data_127_V_2_fu_506 <= data_stream_V_data_7_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln203_reg_3184 == 4'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_120_V_3_fu_510 <= data_stream_V_data_0_V_dout;
        data_121_V_3_fu_514 <= data_stream_V_data_1_V_dout;
        data_122_V_3_fu_518 <= data_stream_V_data_2_V_dout;
        data_123_V_3_fu_522 <= data_stream_V_data_3_V_dout;
        data_124_V_3_fu_526 <= data_stream_V_data_4_V_dout;
        data_125_V_3_fu_530 <= data_stream_V_data_5_V_dout;
        data_126_V_3_fu_534 <= data_stream_V_data_6_V_dout;
        data_127_V_3_fu_538 <= data_stream_V_data_7_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln203_reg_3184 == 4'd4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_120_V_4_fu_542 <= data_stream_V_data_0_V_dout;
        data_121_V_4_fu_546 <= data_stream_V_data_1_V_dout;
        data_122_V_4_fu_550 <= data_stream_V_data_2_V_dout;
        data_123_V_4_fu_554 <= data_stream_V_data_3_V_dout;
        data_124_V_4_fu_558 <= data_stream_V_data_4_V_dout;
        data_125_V_4_fu_562 <= data_stream_V_data_5_V_dout;
        data_126_V_4_fu_566 <= data_stream_V_data_6_V_dout;
        data_127_V_4_fu_570 <= data_stream_V_data_7_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln203_reg_3184 == 4'd5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_120_V_5_fu_574 <= data_stream_V_data_0_V_dout;
        data_121_V_5_fu_578 <= data_stream_V_data_1_V_dout;
        data_122_V_5_fu_582 <= data_stream_V_data_2_V_dout;
        data_123_V_5_fu_586 <= data_stream_V_data_3_V_dout;
        data_124_V_5_fu_590 <= data_stream_V_data_4_V_dout;
        data_125_V_5_fu_594 <= data_stream_V_data_5_V_dout;
        data_126_V_5_fu_598 <= data_stream_V_data_6_V_dout;
        data_127_V_5_fu_602 <= data_stream_V_data_7_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln203_reg_3184 == 4'd6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_120_V_6_fu_606 <= data_stream_V_data_0_V_dout;
        data_121_V_6_fu_610 <= data_stream_V_data_1_V_dout;
        data_122_V_6_fu_614 <= data_stream_V_data_2_V_dout;
        data_123_V_6_fu_618 <= data_stream_V_data_3_V_dout;
        data_124_V_6_fu_622 <= data_stream_V_data_4_V_dout;
        data_125_V_6_fu_626 <= data_stream_V_data_5_V_dout;
        data_126_V_6_fu_630 <= data_stream_V_data_6_V_dout;
        data_127_V_6_fu_634 <= data_stream_V_data_7_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln203_reg_3184 == 4'd7) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_120_V_7_fu_638 <= data_stream_V_data_0_V_dout;
        data_121_V_7_fu_642 <= data_stream_V_data_1_V_dout;
        data_122_V_7_fu_646 <= data_stream_V_data_2_V_dout;
        data_123_V_7_fu_650 <= data_stream_V_data_3_V_dout;
        data_124_V_7_fu_654 <= data_stream_V_data_4_V_dout;
        data_125_V_7_fu_658 <= data_stream_V_data_5_V_dout;
        data_126_V_7_fu_662 <= data_stream_V_data_6_V_dout;
        data_127_V_7_fu_666 <= data_stream_V_data_7_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln203_reg_3184 == 4'd8) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_120_V_8_fu_670 <= data_stream_V_data_0_V_dout;
        data_121_V_8_fu_674 <= data_stream_V_data_1_V_dout;
        data_122_V_8_fu_678 <= data_stream_V_data_2_V_dout;
        data_123_V_8_fu_682 <= data_stream_V_data_3_V_dout;
        data_124_V_8_fu_686 <= data_stream_V_data_4_V_dout;
        data_125_V_8_fu_690 <= data_stream_V_data_5_V_dout;
        data_126_V_8_fu_694 <= data_stream_V_data_6_V_dout;
        data_127_V_8_fu_698 <= data_stream_V_data_7_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln203_reg_3184 == 4'd9) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_120_V_9_fu_702 <= data_stream_V_data_0_V_dout;
        data_121_V_9_fu_706 <= data_stream_V_data_1_V_dout;
        data_122_V_9_fu_710 <= data_stream_V_data_2_V_dout;
        data_123_V_9_fu_714 <= data_stream_V_data_3_V_dout;
        data_124_V_9_fu_718 <= data_stream_V_data_4_V_dout;
        data_125_V_9_fu_722 <= data_stream_V_data_5_V_dout;
        data_126_V_9_fu_726 <= data_stream_V_data_6_V_dout;
        data_127_V_9_fu_730 <= data_stream_V_data_7_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln203_reg_3184 == 4'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_120_V_fu_414 <= data_stream_V_data_0_V_dout;
        data_121_V_fu_418 <= data_stream_V_data_1_V_dout;
        data_122_V_fu_422 <= data_stream_V_data_2_V_dout;
        data_123_V_fu_426 <= data_stream_V_data_3_V_dout;
        data_124_V_fu_430 <= data_stream_V_data_4_V_dout;
        data_125_V_fu_434 <= data_stream_V_data_5_V_dout;
        data_126_V_fu_438 <= data_stream_V_data_6_V_dout;
        data_127_V_fu_442 <= data_stream_V_data_7_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        tmp_data_0_V_reg_3828 <= grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_0;
        tmp_data_10_V_reg_3878 <= grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_10;
        tmp_data_11_V_reg_3883 <= grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_11;
        tmp_data_12_V_reg_3888 <= grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_12;
        tmp_data_13_V_reg_3893 <= grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_13;
        tmp_data_14_V_reg_3898 <= grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_14;
        tmp_data_15_V_reg_3903 <= grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_15;
        tmp_data_1_V_reg_3833 <= grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_1;
        tmp_data_2_V_reg_3838 <= grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_2;
        tmp_data_3_V_reg_3843 <= grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_3;
        tmp_data_4_V_reg_3848 <= grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_4;
        tmp_data_5_V_reg_3853 <= grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_5;
        tmp_data_6_V_reg_3858 <= grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_6;
        tmp_data_7_V_reg_3863 <= grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_7;
        tmp_data_8_V_reg_3868 <= grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_8;
        tmp_data_9_V_reg_3873 <= grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_return_9;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln41_fu_1143_p2 == 1'd0))) begin
        trunc_ln203_reg_3184 <= trunc_ln203_fu_1155_p1;
    end
end

always @ (*) begin
    if ((icmp_ln41_fu_1143_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (io_acc_block_signal_op591 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_0_V_blk_n = data_stream_V_data_0_V_empty_n;
    end else begin
        data_stream_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_0_V_read = 1'b1;
    end else begin
        data_stream_V_data_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_1_V_blk_n = data_stream_V_data_1_V_empty_n;
    end else begin
        data_stream_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_1_V_read = 1'b1;
    end else begin
        data_stream_V_data_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_2_V_blk_n = data_stream_V_data_2_V_empty_n;
    end else begin
        data_stream_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_2_V_read = 1'b1;
    end else begin
        data_stream_V_data_2_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_3_V_blk_n = data_stream_V_data_3_V_empty_n;
    end else begin
        data_stream_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_3_V_read = 1'b1;
    end else begin
        data_stream_V_data_3_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_4_V_blk_n = data_stream_V_data_4_V_empty_n;
    end else begin
        data_stream_V_data_4_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_4_V_read = 1'b1;
    end else begin
        data_stream_V_data_4_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_5_V_blk_n = data_stream_V_data_5_V_empty_n;
    end else begin
        data_stream_V_data_5_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_5_V_read = 1'b1;
    end else begin
        data_stream_V_data_5_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_6_V_blk_n = data_stream_V_data_6_V_empty_n;
    end else begin
        data_stream_V_data_6_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_6_V_read = 1'b1;
    end else begin
        data_stream_V_data_6_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_7_V_blk_n = data_stream_V_data_7_V_empty_n;
    end else begin
        data_stream_V_data_7_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_7_V_read = 1'b1;
    end else begin
        data_stream_V_data_7_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (io_acc_block_signal_op591 == 1'b1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_0_V_blk_n = res_stream_V_data_0_V_full_n;
    end else begin
        res_stream_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (io_acc_block_signal_op591 == 1'b1))) begin
        res_stream_V_data_0_V_write = 1'b1;
    end else begin
        res_stream_V_data_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_10_V_blk_n = res_stream_V_data_10_V_full_n;
    end else begin
        res_stream_V_data_10_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (io_acc_block_signal_op591 == 1'b1))) begin
        res_stream_V_data_10_V_write = 1'b1;
    end else begin
        res_stream_V_data_10_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_11_V_blk_n = res_stream_V_data_11_V_full_n;
    end else begin
        res_stream_V_data_11_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (io_acc_block_signal_op591 == 1'b1))) begin
        res_stream_V_data_11_V_write = 1'b1;
    end else begin
        res_stream_V_data_11_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_12_V_blk_n = res_stream_V_data_12_V_full_n;
    end else begin
        res_stream_V_data_12_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (io_acc_block_signal_op591 == 1'b1))) begin
        res_stream_V_data_12_V_write = 1'b1;
    end else begin
        res_stream_V_data_12_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_13_V_blk_n = res_stream_V_data_13_V_full_n;
    end else begin
        res_stream_V_data_13_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (io_acc_block_signal_op591 == 1'b1))) begin
        res_stream_V_data_13_V_write = 1'b1;
    end else begin
        res_stream_V_data_13_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_14_V_blk_n = res_stream_V_data_14_V_full_n;
    end else begin
        res_stream_V_data_14_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (io_acc_block_signal_op591 == 1'b1))) begin
        res_stream_V_data_14_V_write = 1'b1;
    end else begin
        res_stream_V_data_14_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_15_V_blk_n = res_stream_V_data_15_V_full_n;
    end else begin
        res_stream_V_data_15_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (io_acc_block_signal_op591 == 1'b1))) begin
        res_stream_V_data_15_V_write = 1'b1;
    end else begin
        res_stream_V_data_15_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_1_V_blk_n = res_stream_V_data_1_V_full_n;
    end else begin
        res_stream_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (io_acc_block_signal_op591 == 1'b1))) begin
        res_stream_V_data_1_V_write = 1'b1;
    end else begin
        res_stream_V_data_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_2_V_blk_n = res_stream_V_data_2_V_full_n;
    end else begin
        res_stream_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (io_acc_block_signal_op591 == 1'b1))) begin
        res_stream_V_data_2_V_write = 1'b1;
    end else begin
        res_stream_V_data_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_3_V_blk_n = res_stream_V_data_3_V_full_n;
    end else begin
        res_stream_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (io_acc_block_signal_op591 == 1'b1))) begin
        res_stream_V_data_3_V_write = 1'b1;
    end else begin
        res_stream_V_data_3_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_4_V_blk_n = res_stream_V_data_4_V_full_n;
    end else begin
        res_stream_V_data_4_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (io_acc_block_signal_op591 == 1'b1))) begin
        res_stream_V_data_4_V_write = 1'b1;
    end else begin
        res_stream_V_data_4_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_5_V_blk_n = res_stream_V_data_5_V_full_n;
    end else begin
        res_stream_V_data_5_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (io_acc_block_signal_op591 == 1'b1))) begin
        res_stream_V_data_5_V_write = 1'b1;
    end else begin
        res_stream_V_data_5_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_6_V_blk_n = res_stream_V_data_6_V_full_n;
    end else begin
        res_stream_V_data_6_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (io_acc_block_signal_op591 == 1'b1))) begin
        res_stream_V_data_6_V_write = 1'b1;
    end else begin
        res_stream_V_data_6_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_7_V_blk_n = res_stream_V_data_7_V_full_n;
    end else begin
        res_stream_V_data_7_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (io_acc_block_signal_op591 == 1'b1))) begin
        res_stream_V_data_7_V_write = 1'b1;
    end else begin
        res_stream_V_data_7_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_8_V_blk_n = res_stream_V_data_8_V_full_n;
    end else begin
        res_stream_V_data_8_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (io_acc_block_signal_op591 == 1'b1))) begin
        res_stream_V_data_8_V_write = 1'b1;
    end else begin
        res_stream_V_data_8_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_9_V_blk_n = res_stream_V_data_9_V_full_n;
    end else begin
        res_stream_V_data_9_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (io_acc_block_signal_op591 == 1'b1))) begin
        res_stream_V_data_9_V_write = 1'b1;
    end else begin
        res_stream_V_data_9_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln41_fu_1143_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln41_fu_1143_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (io_acc_block_signal_op591 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((io_acc_block_signal_op298 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((io_acc_block_signal_op298 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (io_acc_block_signal_op298 == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_start = grp_dense_wrapper_ap_fixed_ap_fixed_16_6_5_3_0_config5_s_fu_1009_ap_start_reg;

assign i_in_fu_1149_p2 = (i_in_0_reg_998 + 5'd1);

assign icmp_ln41_fu_1143_p2 = ((i_in_0_reg_998 == 5'd16) ? 1'b1 : 1'b0);

assign io_acc_block_signal_op298 = (data_stream_V_data_7_V_empty_n & data_stream_V_data_6_V_empty_n & data_stream_V_data_5_V_empty_n & data_stream_V_data_4_V_empty_n & data_stream_V_data_3_V_empty_n & data_stream_V_data_2_V_empty_n & data_stream_V_data_1_V_empty_n & data_stream_V_data_0_V_empty_n);

assign io_acc_block_signal_op591 = (res_stream_V_data_9_V_full_n & res_stream_V_data_8_V_full_n & res_stream_V_data_7_V_full_n & res_stream_V_data_6_V_full_n & res_stream_V_data_5_V_full_n & res_stream_V_data_4_V_full_n & res_stream_V_data_3_V_full_n & res_stream_V_data_2_V_full_n & res_stream_V_data_1_V_full_n & res_stream_V_data_15_V_full_n & res_stream_V_data_14_V_full_n & res_stream_V_data_13_V_full_n & res_stream_V_data_12_V_full_n & res_stream_V_data_11_V_full_n & res_stream_V_data_10_V_full_n & res_stream_V_data_0_V_full_n);

assign res_stream_V_data_0_V_din = tmp_data_0_V_reg_3828;

assign res_stream_V_data_10_V_din = tmp_data_10_V_reg_3878;

assign res_stream_V_data_11_V_din = tmp_data_11_V_reg_3883;

assign res_stream_V_data_12_V_din = tmp_data_12_V_reg_3888;

assign res_stream_V_data_13_V_din = tmp_data_13_V_reg_3893;

assign res_stream_V_data_14_V_din = tmp_data_14_V_reg_3898;

assign res_stream_V_data_15_V_din = tmp_data_15_V_reg_3903;

assign res_stream_V_data_1_V_din = tmp_data_1_V_reg_3833;

assign res_stream_V_data_2_V_din = tmp_data_2_V_reg_3838;

assign res_stream_V_data_3_V_din = tmp_data_3_V_reg_3843;

assign res_stream_V_data_4_V_din = tmp_data_4_V_reg_3848;

assign res_stream_V_data_5_V_din = tmp_data_5_V_reg_3853;

assign res_stream_V_data_6_V_din = tmp_data_6_V_reg_3858;

assign res_stream_V_data_7_V_din = tmp_data_7_V_reg_3863;

assign res_stream_V_data_8_V_din = tmp_data_8_V_reg_3868;

assign res_stream_V_data_9_V_din = tmp_data_9_V_reg_3873;

assign start_out = real_start;

assign trunc_ln203_fu_1155_p1 = i_in_0_reg_998[3:0];

endmodule //dense_array_array_ap_fixed_16_6_5_3_0_16u_config5_s
